### PR TITLE
Lobsters instance can be passed as CLI argument

### PR DESCRIPTION
**Pull request by southerntofu**
Thanks for gopher://tilde.news :)

### CODE REVIEW

**Comment by julienXX** [comment]
Thanks a lot for the PR! This is looking good to me. Could you just bring back Cargo.lock? See https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by southerntofu** [comment]
I reintroduced `Cargo.lock` in the PR. With this patch, the build in release mode increases from 6.5 to 8.6 MB. Here's the cargo bloat reports:

master branch
```
 File  .text     Size Name
 6.9%  24.4% 456.4KiB std
 3.4%  12.1% 226.3KiB regex
 3.3%  11.8% 220.7KiB regex_syntax
 3.2%  11.2% 209.7KiB h2
 2.8%   9.9% 185.7KiB hyper
 1.7%   6.1% 113.6KiB futures
 1.0%   3.6%  67.9KiB serde_json
 0.8%   2.9%  55.1KiB http
 0.5%   1.9%  36.0KiB [Unknown]
 0.5%   1.9%  35.1KiB chrono
 0.5%   1.9%  35.0KiB tokio_reactor
 0.5%   1.8%  33.8KiB tokio_threadpool
 0.4%   1.4%  26.7KiB futures_cpupool
 0.3%   0.9%  17.1KiB tokio
 0.2%   0.7%  13.9KiB mio
 0.2%   0.7%  13.9KiB bytes
 0.2%   0.7%  13.6KiB openssl
 0.2%   0.7%  13.1KiB gophsters
 0.2%   0.7%  12.3KiB tokio_timer
 0.2%   0.7%  12.2KiB tokio_tcp
28.3% 100.0%   1.8MiB .text section size, the file size is 6.4MiB
```

cli-args branch
```
 File  .text     Size Name
 7.0%  22.9% 612.9KiB std
 3.6%  11.9% 318.4KiB clap
 2.7%   8.7% 232.4KiB regex
 2.7%   8.7% 231.5KiB h2
 2.5%   8.2% 219.0KiB regex_syntax
 2.3%   7.6% 203.3KiB hyper
 1.5%   4.7% 126.7KiB futures
 1.0%   3.1%  84.1KiB unicode_normalization
 0.8%   2.6%  69.4KiB aho_corasick
 0.7%   2.3%  61.4KiB http
 0.7%   2.2%  58.8KiB serde_json
 0.5%   1.6%  42.9KiB tokio_threadpool
 0.5%   1.5%  40.8KiB url
 0.4%   1.4%  36.1KiB [Unknown]
 0.4%   1.3%  35.1KiB chrono
 0.4%   1.2%  32.5KiB tokio_reactor
 0.3%   1.0%  26.7KiB futures_cpupool
 0.3%   0.9%  22.8KiB idna
 0.2%   0.8%  20.7KiB tokio
 0.2%   0.6%  15.0KiB gophsters
30.6% 100.0%   2.6MiB .text section size, the file size is 8.5MiB
```

**Comment by julienXX** [comment]
When trying your changes there is an error regarding json parsing. I'll check what's wrong.

**Comment by southerntofu** [comment]
> an error regarding json parsing

Parsing some pages from lobste.rs also failed, because some comments had negative scores and the score was declared `u8`. Changing it to `i8` fixed the issue for me.

Funny we did not find a negative score to hit this bug before :D

**Comment by southerntofu** [comment]
Oh also i snuck in some stuff in the PR by mistake changing user structure that's what broke the download.

Also, running the code often produces:

```
thread 'tokio-runtime-worker-3' panicked at 'nested tokio::run: EnterError { reason: "attempted to run an executor while another executor is already running" }', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Done.
```

As the message explains, running a tokio inside a tokio is wrong. I got rid of async hyper+tokio in favor of sync reqwest+rayon in an [experimental branch](https://github.com/southerntofu/gophsters/tree/templates). I could introduce such changes (without the tera templating) in this PR or as a separate PR if that's ok with you.

**Comment by julienXX** [comment]
Let’s do separate PRs if you don’t mind. Thanks!

**Comment by southerntofu** [comment]
Sure! Could you merge this PR even if tokio collision makes it panick so i can use this as base for the next PR?

**Comment by julienXX** [comment]
I'm trying to revert some crate updates to have at least a working master branch.

**Comment by julienXX** [comment]
It works, I'll merge your branch, apply the Cargo.lock revert and then you will have to re-update crates if needed.

**Comment by julienXX** [comment]
Done :)

**Comment by southerntofu** [comment]
Thanks!

**Comment by southerntofu** [comment]
Wow so much commit history spam because of me.. don't hestaite to squash commits together for the next PR ;)

**Comment by julienXX** [comment]
Yes I will rewrite history a bit!

**Comment by julienXX** [comment]
I cleaned the history a bit :+1:

**Pull request merged**
